// --------------------------------------------------------------
// -                        測試腳本                             -
// --------------------------------------------------------------
// 這些腳本是用於回歸測試的目的。

npc: npc/test/infinite_warp.txt
npc: npc/test/OnInterInit.txt
npc: npc/test/npc_test_checkweight.txt
