// --------------------------------------------------------------
// -                         公會戰                         -
// --------------------------------------------------------------

// ----------------------- 公會戰 (WoE) ----------------------
// - 公會戰時間設定
npc: npc/guild/agit_controller.txt 
// - 公會 NPC 範本文件
npc: npc/guild/agit_main.txt
// - 艾爾帕蘭
npc: npc/guild/aldeg_cas01.txt
npc: npc/guild/aldeg_cas02.txt
npc: npc/guild/aldeg_cas03.txt
npc: npc/guild/aldeg_cas04.txt
npc: npc/guild/aldeg_cas05.txt
// - 吉芬
npc: npc/guild/gefg_cas01.txt
npc: npc/guild/gefg_cas02.txt
npc: npc/guild/gefg_cas03.txt
npc: npc/guild/gefg_cas04.txt
npc: npc/guild/gefg_cas05.txt
// - 斐揚
npc: npc/guild/payg_cas01.txt
npc: npc/guild/payg_cas02.txt
npc: npc/guild/payg_cas03.txt
npc: npc/guild/payg_cas04.txt
npc: npc/guild/payg_cas05.txt
// - 普隆德拉
npc: npc/guild/prtg_cas01.txt
npc: npc/guild/prtg_cas02.txt
npc: npc/guild/prtg_cas03.txt
npc: npc/guild/prtg_cas04.txt
npc: npc/guild/prtg_cas05.txt
// - 寶箱房保護
//npc: npc/guild/trs_rp.txt

// --------------- 公會戰 第二季 (WoE SE) ---------------
// - WoE SE 時間設定
npc: npc/guild2/agit_start_se.txt
// - 公會 NPC 範本文件
npc: npc/guild2/agit_main_se.txt
// - 城鎮旗幟
npc: npc/guild2/guild_flags.txt
// - 阿盧納貝茲
npc: npc/guild2/arug_cas01.txt
npc: npc/guild2/arug_cas02.txt
npc: npc/guild2/arug_cas03.txt
npc: npc/guild2/arug_cas04.txt
npc: npc/guild2/arug_cas05.txt
// - 秀發茲發德
npc: npc/guild2/schg_cas01.txt
npc: npc/guild2/schg_cas02.txt
npc: npc/guild2/schg_cas03.txt
npc: npc/guild2/schg_cas04.txt
npc: npc/guild2/schg_cas05.txt
