// --------------------------------------------------------------
// -           rAthena Pre-Renewal 主要腳本檔案                   -
// --------------------------------------------------------------
//  這個新系統的構想是為了讓腳本更有條理，
//  因為舊系統將所有 NPC 放在同一個檔案中顯得相當雜亂。
//  現在腳本已根據類型分類到不同的檔案中。
//  自訂腳本現在位於 scripts_custom.conf，所有其他
//  腳本皆被視為「官方」腳本。您應該將您的 NPC
//  放入 scripts_custom.conf 以符合此趨勢。
//
//  感謝，
//  Ancyker 以及 rAthena 團隊的所有成員
//
//  註：所有位於雙斜線 "//" 右側的文字皆為「註解」。
//  任何被註解的文字都不會被伺服器解析，
//  僅作為資訊/參考之用。
//
// --------------------------------------------------------------

// ------------------ 全域腳本函數 ------------------
// 被許多腳本使用的工具型函數。
npc: npc/other/Global_Functions.txt

// -------------------- 商城功能函數 ---------------------
// 供物品資料庫 (Item Database) 中的商城物品使用。
npc: npc/other/CashShop_Functions.txt

// ------------------- 通用腳本檔案 ----------------------
import: npc/scripts_athena.conf
import: npc/scripts_guild.conf
import: npc/scripts_jobs.conf
import: npc/scripts_mapflags.conf
import: npc/scripts_monsters.conf
import: npc/scripts_warps.conf

// ----------------- Pre-Renewal 腳本檔案 -------------------
import: npc/pre-re/scripts_athena.conf
import: npc/pre-re/scripts_jobs.conf
import: npc/pre-re/scripts_mapflags.conf
import: npc/pre-re/scripts_monsters.conf
import: npc/pre-re/scripts_warps.conf

// 測試回歸 (Regressions) 等項目
//import: npc/scripts_test.conf

// ------------------- 自訂腳本檔案 ----------------------
// - 您的 NPC 請放在這個檔案！
import: npc/scripts_custom.conf
